[project]
name = "regression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
<<<<<<< HEAD
    "kagglehub[pandas-datasets]>=1.0.0",
=======
    "kagglehub>=1.0.0",
>>>>>>> develop
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
